apiVersion: v1
kind: Pod
metadata:
  name: private-registry
  labels:
    name: private-registry
spec:
  containers:
  - name: private-registry-app
    image: danielstefanelli/node-app:latest
  imagePullSecrets:
    - name: registrycredentials
