apiVersion: types.kubefed.io/v1beta1
kind: FederatedDeployment
metadata:
  name: hello-app
  namespace: hello-app
spec:
  placement:
    clusterSelector: {}
  overrides:
    - clusterName: host-cluster
      clusterOverrides:
      - path: "/spec/replicas"
        value: 1
  template:
    metadata:
      name: hello-app
      labels:
        app: hello-app
    spec:
      replicas: 2
      selector:
        matchLabels:
          app: hello-app
      template:
        metadata:
          labels:
            app: hello-app
        spec:
          containers:
          - name: hello-app
            image: "gcr.io/google-samples/hello-app:2.0"
            ports:
            - containerPort: 8080
              protocol: TCP