apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deployment
  namespace: sample-apps
  labels:
    app: sample-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - name: http
          containerPort: 80
      nodeSelector:
        kubernetes.io/os: linux