apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: basic-cluster
  region: eu-west-3
nodeGroups:
  - name: ng-1
    labels: { role: workersA }
    instanceType: m5.large
    desiredCapacity: 3
    volumeSize: 80
    ssh:
      allow: true # usara ~/.ssh/id_rsa.pub como el ssh key por defecto
  - name: ng-2
  labels: { role: workersB }
    instanceType: m5.large
    desiredCapacity: 2
    volumeSize: 100
    ssh:
      allow: true
