---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-lab
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/danicaliforrnia/kubernetes-lab
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tema-5/nginx-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kubernetes-lab
  install:
    createNamespace: true
  interval: 30s
  targetNamespace: demo
  upgrade:
    remediation:
      retries: 2
  rollback:
    timeout: 2m
    disableWait: false
    disableHooks: false
    recreate: false
    force: false
    cleanupOnFail: false
