---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: flux-system
spec:
  chart:
    spec:
      chart: tema-5/nginx-chart
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: kubernetes-lab
  interval: 30s
  targetNamespace: demo
