apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: web
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      serviceAccountName: app-sa
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      containers:
        - name: app
          image: nginx
          volumeMounts:
          - mountPath: /var/run/secrets/tokens
            name: my-projected-token