apiVersion: v1
kind: Pod
metadata:
  name: workload-identity-test
  namespace: web
spec:
  containers:
  - name: workload-identity-test
    image: google/cloud-sdk:slim
    command: ["sleep", "infinity"]
  serviceAccountName: app-sa
  nodeSelector:
    iam.gke.io/gke-metadata-server-enabled: "true"