apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: web
spec:
  serviceAccountName: app-sa
  containers:
  - name: count
    image: busybox:1.28
    command:
      - sleep
      - "3600"  
  restartPolicy: Always