apiVersion: v1
kind: Namespace
metadata:
  name: web
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  namespace: web
  annotations:
    iam.gke.io/gcp-service-account: "app-sa@cursos-imagina.iam.gserviceaccount.com"