apiVersion: constraints.gatekeeper.sh/v1beta1
kind: AppLabel
metadata:
  name: app-pods-warn
spec:
  enforcementAction: warn
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    excludedNamespaces:
    - kube-system