---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kubernetes-lab
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/danicaliforrnia/kubernetes-lab
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kubernetes-lab
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./nginx-chart
  prune: true
  sourceRef:
    kind: GitRepository
    name: kubernetes-lab
