apiVersion: batch/v1
kind: Job
metadata:
  name: countdown
spec:
  completions: 50
  parallelism: 10
  template:
    metadata:
      name: countdown
    spec:
      containers:
      - name: counter
        image: ubuntu
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
      restartPolicy: Never