apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:            
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: minikube-m02