apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: my-eks-cluster
  region: eu-west-3
nodeGroups:
  - name: ng-1
    labels: { role: workersA }
    instanceType: m5.large
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    volumeSize: 80
    ssh:
      allow: true
  - name: ng-2
    labels: { role: workersB }
    instanceType: m5.large
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    volumeSize: 100
    ssh:
      allow: true
