apiVersion: v1
kind: Pod
metadata:
  name: termination
spec:
  containers:
    - name: termination-container
      image: debian
      command: ["/bin/sh"]
      terminationMessagePath: "/tmp/termination-log"
      args: ["-c", "sleep 10 && echo Sleep Finished > /tmp/termination-log"]