apiVersion: v1
kind: Pod
metadata:
  name: termination
spec:
  containers:
    - name: termination-container
      image: debian
      command: ["/bin/sh"]
      terminationMessagePolicy: FallbackToLogsOnError
      args: ["-c", "sleep 10"]