apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app-demo
  template:
    metadata:
      labels:
        app: node-app-demo
    spec:
      containers:
      - name: node-app-demo
        image: danielstefanelli/node-app:latest
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 1024Mi
          requests:
            memory: 256Mi