apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 6
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 3
  template:
    metadata: 
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx:1.21.0-alpine
          ports:
            - containerPort: 80