apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  template:
    metadata: 
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nginx:1.20.0-alpine
          ports:
            - containerPort: 80