name: Node.js CI

on:
  push:
    branches: [ master ]

defaults:
 run:
  working-directory: ./tema-5/node-app

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      node-version: 20.x
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ env.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Build app
      run: npm run build --if-present

  push:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
    
    - name: Run the image in a container
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo:latest
        run: |
          echo "Testing the nodejs app"
          curl http:localhost:8080
          echo ${{ steps.docker_build.outputs.digest }}