name: Docker Hub Deployment

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
    - 'tema-5/node-app/**'

defaults:
 run:
  working-directory: 'tema-5/node-app'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.x
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'tema-5/node-app/package-lock.json'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

  push:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: tema-5/node-app
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
    
    - run: echo ${{ steps.docker_build.outputs.digest }}

    - name: Run the image in a container
      uses: addnab/docker-run-action@v3
      with:
        image: ${{ secrets.DOCKERHUB_USERNAME }}/node-app:latest
        run: |
          echo "Testing the nodejs app"
          curl http://localhost:8080
          echo ${{ steps.docker_build.outputs.digest }}