name: Node.js CI

on:
  push:
    branches: [ master ]
    paths:
    - './tema-5/node-app'


defaults:
 run:
  working-directory: ./tema-5/node-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
    - run: npm install
    - run: npm run test
    - run: npm run build --if-present