name: Terraform IaC

on:
  workflow_dispatch:
  push:
    paths:
    - 'tema-4/gke-2/**'
    branches:
      - master

defaults:
 run:
  working-directory: 'tema-4/gke-2'

jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: 'Authenticate to Google Cloud'
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CE_CREDENTIALS }}'

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init
          
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -var="project_id=${{ vars.PROJECT_ID }}"
        continue-on-error: true

      - name: Terraform Plan Status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'push' 
        run: terraform apply -auto-approve -var="project_id=${{ vars.PROJECT_ID }}"