apiVersion: v1
kind: PersistentVolume
metadata:
  name: webapp-pv-volume-2
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Delete
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"