apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: test-role
  namespace: namespace1
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list